# Generated by Django 4.2.6 on 2023-12-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name_plural": "Contacts"},
        ),
    ]
